### ISSUE TITLE
Update Operation 

### ISSUE THREAD

**Issue by adamdxn** [Denpoly/ticketBookingCPSC304#3]
Provide an interface for the user to specify some input for the update operation.

**Comment by adamdxn** [comment]
Update a performers information specified by the performers stage_name

pid
stage_name
email
industry
postal_code
mobile_number

**Comment by mattmemme** [comment]
@mattmemme

**Comment by mattmemme** [comment]
Update the attributes of a single performer tuple in the performers table.
