### ISSUE TITLE
Selection

### ISSUE THREAD

**Issue by adamdxn** [Denpoly/ticketBookingCPSC304#4]
Create one query of this category and provide an interface for the user to specify the values of the selection conditions to be returned.

Example:
SELECT  …
FROM     …
WHERE  Field1 = :Var1 AND Field2 > :Var2

**Comment by adamdxn** [comment]
Could be something like this: "Return the first names of all customers who have more that a specified amount of points and in a specified area code (like 604 or 250)"

SELECT first_name
FROM Customer
WHERE points > 20 AND area_code ...

**Comment by mattmemme** [comment]
Get all events where the specified performer is performing.
