### ISSUE TITLE
Projection

### ISSUE THREAD

**Issue by adamdxn** [Denpoly/ticketBookingCPSC304#5]
Create one query of this category, with 3-5 attributes in the projection condition, but not SELECT *.  If you wish, you can have the user select the attributes from a drop-down list, but we will accept hard-code SELECT statement for the table(s) in question.

**Comment by adamdxn** [comment]
"Select the desired information for a customer" (with a dropdown menu)

Example...
SELECT first_name, last_name, username, email, points
FROM Customer

**Comment by mattmemme** [comment]
Get all event titles and their venue names for events that meet the criteria specified by the user.
