### ISSUE TITLE
Join

### ISSUE THREAD

**Issue by adamdxn** [Denpoly/ticketBookingCPSC304#6]
Create one query in this category, which joins at least 2 tables and performs a meaningful query, and provide an interface for the user to execute this query.  The user must provide at least one value to qualify in the WHERE clause (e.g. join the Customer and the Transaction table to find the names and phone numbers of all customers who have purchased a specific item).

**Comment by adamdxn** [comment]
Example:

SELECT first_name, last_name
FROM Customer C, Purchase_Order PO
WHERE total_cost > (user input)

**Comment by adamdxn** [comment]
@adamdxn

**Comment by mattmemme** [comment]
Gets all customers that made a purchase order less than the money amount specified by the user in the prompt.
